# Generated by Django 3.2.12 on 2022-03-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_auto_20220225_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='forget_otp',
            name='secret_key',
            field=models.CharField(default='', max_length=50),
        ),
    ]
